"""Add bookings table

Revision ID: 331df797ed0a
Revises: add_user_refresh_token
Create Date: 2026-01-25 03:26:36.738165

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331df797ed0a'
down_revision: Union[str, Sequence[str], None] = 'add_user_refresh_token'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_stage_history', 'changed_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_lead_stage_history_changed_by'), 'lead_stage_history', ['changed_by'], unique=False)
    op.drop_constraint(op.f('lead_stage_history_lead_id_fkey'), 'lead_stage_history', type_='foreignkey')
    op.drop_constraint(op.f('lead_stage_history_changed_by_fkey'), 'lead_stage_history', type_='foreignkey')
    op.create_foreign_key(None, 'lead_stage_history', 'users', ['changed_by'], ['id'])
    op.create_foreign_key(None, 'lead_stage_history', 'leads', ['lead_id'], ['id'])
    op.drop_column('lead_stage_history', 'modified')
    op.alter_column('lead_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('lead_tags_tag_id_fkey'), 'lead_tags', type_='foreignkey')
    op.drop_constraint(op.f('lead_tags_lead_id_fkey'), 'lead_tags', type_='foreignkey')
    op.create_foreign_key(None, 'lead_tags', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'lead_tags', 'tags', ['tag_id'], ['id'])
    op.alter_column('leads', 'company',
               existing_type=sa.VARCHAR(length=200),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'organization',
               existing_type=sa.VARCHAR(length=200),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'website',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('leads', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_leads_company'), table_name='leads')
    op.create_index('ix_leads_user_active', 'leads', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_leads_user_stage', 'leads', ['user_id', 'stage'], unique=False)
    op.drop_constraint(op.f('leads_user_id_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_assigned_to_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'])
    op.drop_column('leads', 'modified')
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_tag_name_user'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index('ix_tags_user_name', 'tags', ['user_id', 'name'], unique=True)
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.drop_column('tags', 'modified')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tags', sa.Column('modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_tags_user_name', table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_unique_constraint(op.f('uq_tag_name_user'), 'tags', ['name', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tags', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('leads', sa.Column('modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_assigned_to_fkey'), 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('leads_user_id_fkey'), 'leads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_leads_user_stage', table_name='leads')
    op.drop_index('ix_leads_user_active', table_name='leads')
    op.create_index(op.f('ix_leads_company'), 'leads', ['company'], unique=False)
    op.alter_column('leads', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('leads', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('leads', 'website',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('leads', 'organization',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('leads', 'company',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_constraint(None, 'lead_tags', type_='foreignkey')
    op.drop_constraint(None, 'lead_tags', type_='foreignkey')
    op.create_foreign_key(op.f('lead_tags_lead_id_fkey'), 'lead_tags', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lead_tags_tag_id_fkey'), 'lead_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lead_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('lead_stage_history', sa.Column('modified', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lead_stage_history', type_='foreignkey')
    op.drop_constraint(None, 'lead_stage_history', type_='foreignkey')
    op.create_foreign_key(op.f('lead_stage_history_changed_by_fkey'), 'lead_stage_history', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('lead_stage_history_lead_id_fkey'), 'lead_stage_history', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lead_stage_history_changed_by'), table_name='lead_stage_history')
    op.alter_column('lead_stage_history', 'changed_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
